apiVersion: apps/v1
kind: Deployment
metadata:
  name: mibanco-app
  labels:
    app: mibanco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mibanco
  template:
    metadata:
      labels:
        app: mibanco
    spec:
      containers:
        - name: mibanco-app
          image: mibancoacr.azurecr.io/mibanco:latest
          ports:
            - containerPort: 8080