name: CI/CD Pipeline

on:
  #push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Compilar la aplicación
        run: mvn clean package
      
      - name: Ejecutar pruebas
        run: mvn test
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #- name: Azure login
      #  uses: azure/login@v2
      #  with:
      #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Construir y subir imagen a ACR
        run: |
          az acr login --name mibancoacr
          docker build -t mibancoacr.azurecr.io/mibanco:latest .
          docker push mibancoacr.azurecr.io/mibanco:latest

      - name: Desplegar en AKS
        run: |
          az aks get-credentials --resource-group mibanco-rg --name mibanco-aks
          kubectl apply -f k8s/

      - name: Registrar API en API Management
        run: |
          az apim api import --resource-group mibanco-rg --service-name mibanco-apim --path "mibanco" --api-id "mibanco-api" --wsdl-url "http://mibanco.local/swagger.yaml"